[project]
name = "dadapy"
version = "0.3.4"
description = "Distance-based Analysis of DAta-manifolds in python"
authors = [{ name = "DADApy author"}]
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["numpy", "scipy", "scikit-learn", "matplotlib",
                "seaborn", "tqdm", "networkx",
                'jax==0.4.30; python_version < "3.13"',
                'jax; python_version >= "3.13"',
                'jaxlib==0.4.30; python_version < "3.13"',
                'jaxlib; python_version >= "3.13"',
                'flax==0.8.5; python_version < "3.13"',
                'flax; python_version >= "3.13"']

[project.urls]
homepage = "https://github.com/sissa-data-science/DADApy"
documentation = "https://dadapy.readthedocs.io/"
repository = "https://github.com/sissa-data-science/DADApy"

[project.optional-dependencies]
dev = ["tox", "black", "isort", "pytest"]

[build-system]
requires = ["setuptools>=77", "numpy"]
build-backend = "setuptools.build_meta"

[tool.tox]
envlist = ["py310", "py311", "py312", "py313", "py314"]

[tool.coverage.run]
source_pkgs = ["dadapy"]
omit = ["dadapy/plot.py"]

[tool.coverage.paths]
source = [
    "dadapy/",
    "*/site-packages/dadapy/",
]
